### ISSUE TITLE
Well done!

### ISSUE THREAD

**Issue by mczac** [dehsgr/homebridge-mobilealerts#1]
Thanks for the plug-in.
I did a quick workaround for 10100 sensor prior to your plug-in
var res = request(this.http_method, this.url, {});
	if(res.statusCode > 400){
	  this.log('HTTP power function failed');
	  callback(error);
	} else {
          const $ = cheerio.load(res.body);
          var repeat=0;
          $('h4').each(function() {
             repeat++;
             if (repeat==3){
               TC = parseFloat($(this).text());
             }
          })

**Comment by dehsgr** [comment]
Hi @mczac,

I would like you to clarify where your workaround is placed in code and which unexpected behavior is fixed. Currently I‘m not able to recognize, what your specific problem is.

Thanks,

@dehsgr

PS: Thanks for the compliment! ;-)

**Comment by mczac** [comment]
There is no issue. I just shared with you short snippet that I used for 10100 sensor. 
Thanks again for the plugin. 

@mczac

**Comment by dehsgr** [comment]
Ah, okay. Now I see. Thanks again for sharing. ;-)
