### ISSUE TITLE
Add support for fakegato-history

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#10]
It would be really nice to have historical data, which seems possible using fakegato-history https://github.com/simont77/fakegato-history
That would make the historical data nicely available in the Eve Home app (this is apparently not supported in the Apple Home app)

**Comment by dehsgr** [comment]
Sorry @jerome71, but this project focuses only on supporting Apple‘s Home App. Thanks for your understanding.

**Comment by Mart-Muc** [comment]
i just  joined 10 min ago github because of homebridge project. 
Is it possible to create a branch with fakegato-history. Would love to work on it with some suporting/more experienced users.

**Comment by dehsgr** [comment]
You are welcome to make your implementation and push it to this repository.

**Comment by Mart-Muc** [comment]
never worked with git before.  Ill try to install Github Desktop and push my first test 
(added already Configparameter "pollingInterval", course Mobileallert standard sensors r updating only every 7min)
pls be patient ;-)
PS: gibt's ne Möglichkeit hier direkt in Kontakt zueinander zu treten?

**Comment by dehsgr** [comment]
> PS: gibt's ne Möglichkeit hier direkt in Kontakt zueinander zu treten?
z.B. via E-Mail über meinen Nickname at outlook.com. :-)
