### ISSUE TITLE
Sometimes when I restart Homebridge the sensors disappear in Home App

### ISSUE THREAD

**Issue by octaviz** [dehsgr/homebridge-mobilealerts#15]
It does not always happen but if for some reason I have to restart Homebridge all the sensors disappear from everywhere, to solve it I have to put the plugin in "reset" mode so that HB can recreate them. It's funny because I also use them in Home Assistant with a similar system using Scrape and it has never happened to me. This happened to me already with the version of the plugin older than the new one a few days ago.

What I have noticed is that the web measurements.mobile-alerts.eu where the information is extracted from is sometimes down for a few minutes, not if it has anything to do with it.

`
[7/7/2020, 11:39:05 AM] [MobileAlerts] Fetching Data...
[7/7/2020, 11:39:05 AM] [MobileAlerts] Updating Accessory Data...
[7/7/2020, 11:39:05 AM] [MobileAlerts] Could not get Data for Sensor Room!
[7/7/2020, 11:39:05 AM] [MobileAlerts] Could not get Data for Sensor Terraza
`

**Comment by dehsgr** [comment]
The service depends on measurements.mobile-alerts.eu being online. So if it is down you cannot receive any data.

**Comment by octaviz** [comment]
It is logical that if the web is down the sensors do not work, but this that the sensors disappear after a restart is normal?
Thanks!

**Comment by dehsgr** [comment]
No, disappearing sensors aren't normal. But this issue isn't reproducable to me. I assume this is an issue with your homebridge.

**Comment by octaviz** [comment]
Ok, I will check my installation.

Thanks
