### ISSUE TITLE
MA10800

### ISSUE THREAD

**Issue by HolgerOnGithub** [dehsgr/homebridge-mobilealerts#16]
Hello,
Thanks for your PlugIn to my Homebridge. I use the Magnet Contact from TFA „MA10800“ can you implement on this Plug in?
Best regards
Holger

**Comment by dehsgr** [comment]
If you would provide an Sensor ID and/or MA ID I'll see how I can assist you. ;-)

**Comment by HolgerOnGithub** [comment]
https://www.conrad.de/de/p/techno-line-ma-10800-3-kontaktsensor-1396673.html

I thought the MA10800 was the ID : - /

**Comment by dehsgr** [comment]
Sorry. I need a serial of a working sensor for implementation as I don't have such sensor. :-/

**Comment by dehsgr** [comment]
Okay. I found a sample sensor serial on MA website. Lucky guy. ;-)

**Comment by HolgerOnGithub** [comment]
Not working after the update


See attached Photo

**Comment by dehsgr** [comment]
1.) I Can't see any photo.
2.) A bit more information could be useful.
3.) A small thank you would be nice, as I do this at no cost for you. ;-)

**Comment by dehsgr** [comment]
One more thing: a real sensor serial could be useful as mentioned above. ;-)

**Comment by HolgerOnGithub** [comment]
1023CB5715C8 Door
102CFEE70F96 Window Bad
102274DC5BF8 Kitchen right
102B2123CF83 Kitchen left
And 15 more I have :D

**Comment by HolgerOnGithub** [comment]
if it works I would be happy to support you with a donation.

**Comment by HolgerOnGithub** [comment]
![Uploading 87985056...]()

**Comment by dehsgr** [comment]
Now I'm confused, but I'm happy it's working now. A donation isn't necessary. A small thank you is enough. ;-)

So I can close now. Am I right?

**Comment by dehsgr** [comment]
Oh, sorry. My mistake - you wrote "if it works". :-)

**Comment by dehsgr** [comment]
Sorry, but I need some more info. If I add WindowBad it shows open as on measurement site. Door shows closed correctly too. Where is the issue?

**Comment by HolgerOnGithub** [comment]
with me all sensors are shown in the home app as "not supported". no matter whether I open or close the contacts. I see all status changes in my own TFA app

**Comment by HolgerOnGithub** [comment]
![image](https://user-images.githubusercontent.com/68544715/87992302-41008d00-cae8-11ea-96da-2830627c7422.png)

**Comment by HolgerOnGithub** [comment]
![image](https://user-images.githubusercontent.com/68544715/87992324-51b10300-cae8-11ea-8967-0d859b6d3a15.png)

**Comment by HolgerOnGithub** [comment]
![image](https://user-images.githubusercontent.com/68544715/87992360-6392a600-cae8-11ea-8fd0-b56bee733536.png)

**Comment by HolgerOnGithub** [comment]
![image](https://user-images.githubusercontent.com/68544715/87992565-db60d080-cae8-11ea-8a1f-965ec51d919a.png)

**Comment by HolgerOnGithub** [comment]
![image](https://user-images.githubusercontent.com/68544715/87993167-1f080a00-caea-11ea-95b6-4100059c94d1.png)

**Comment by dehsgr** [comment]
Please contact me via mail: dehsgr [a] outlook.com

**Comment by dehsgr** [comment]
Issue is related to data transfer between TFA and Mobile Alerts.
