### ISSUE TITLE
Feature Request: MA10650PRO

### ISSUE THREAD

**Issue by meistermolli** [dehsgr/homebridge-mobilealerts#21]
Hi,
I have found your nice Plugin and now I am able to see the temperature and humidity in my HomeKit.

Do you thing it ist Possible to get the MA10650PRO / WH 30.3306.02 inside the Plugin?
I Use the TFA version of this Rain sensor and the set MA10050

The next Sensor would be the Wind sensor MA10660 / WH 30.3307.02.

Iam Able to see them in Homekit. (Just an Icon: House) But I am not able to the them in Eve App.

Thanks

**Comment by dehsgr** [comment]
I'm sorry but I will only support native HomeKit objects. Rain and wind sensors would be displayed as unsupported devices. Thanks for your understanding.

**Comment by meistermolli** [comment]
is ist possible to make them invisible? or not to match them to HomeKit? Because they are already there in HomeKit!

**Comment by dehsgr** [comment]
Sorry, but you ask me for an implementation and the sensors are already there? What I am missing? ;-)

You might install Eve app. There might your data being displayed. 

Alternatively you should provide me with some more information (such as your iPhone ID via dehsgr at sign outlook dot sign com) and some clarification what you expect and what not.
