### ISSUE TITLE
Support for MA 10450?

### ISSUE THREAD

**Issue by Freezle12** [dehsgr/homebridge-mobilealerts#22]

**Comment by Freezle12** [comment]
Hello dehsgr,
I would love to integrate my MA 10450 into the HomeKit system.
Is there any possible way to get this to work with your Homebridge-Plugin?
Thank you in advance!
Best regards,
 Freezle12

**Comment by dehsgr** [comment]
Hi,

this should work. You might send me your phone ID (where sensor is assigned to) to dehsgr at-sign outlook dot com. So I can take a look.

**Comment by dehsgr** [comment]
@Freezle12 I would like you to check if my changes from this repository are ensuring sensor is working in your homebridge now. After confirmation I will publish these changes via NPM.

**Comment by Freezle12** [comment]
@dehsgr it works like a charm!
Thank you very much !!!

**Comment by Freezle12** [comment]
Should it be possible to use the sensors as a trigger for automations in HomeKit?
Because that does not work..
Both sensors (indoor and outdoor)show me their temperature in HomeKit, but when I create a new automation, only my Eve window sensor can be used as a trigger..

thank you in advance!

**Comment by dehsgr** [comment]
Nope. This is not an expected behavior. Maybe you can try to accomplish this via Eve app?

**Comment by Freezle12** [comment]
Yes!
From the eve app it works👍🏻
But for people with no eve products in their system this is not an ideal solution..
Anyways, I can work with that, thank you!

**Comment by dehsgr** [comment]
@Freezle12 feel free to discuss this with Apple. These are HomeKit restrictions / missing features within the Home app at all. I can't do really nothing here.

Eve app is usable for all users. This is regardless of owning any Eve products. It is a more feature-rich app. Another alternative could be using Apple's shortcut app.
