### ISSUE TITLE
HomePod cannot get temperature sensor while iOS,iPadOS, watchOS and macOS devices can

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#23]
When I ask Siri about the temperature in the living room on my HomePod mini, it answers that it hasn't received an answer from the system, or that it hasn't found anything in the living room of my home this time (I translated answers from French).

The same request on my iPhone, iPad, Mac, Apple Watch via Siri or in the Home app gives me the correct temperature.

Other homebridge requests on the same HomePod mini work OK (they are to command and get the status of a Logitech Harmony remote) work without issue.

I had a similar issue with all of Homebridge via HomePod until I changed the default mDNS broadcaster for HomeBridge to Bonjour HAP instead of Ciao in HomeBridge settings.
If Homebridge always uses Ciao instead of the HomeBridge default broadcaster  that could be the reason for the issue.

**Comment by dehsgr** [comment]
So what do you expect from my site? I cannot see any issue here affecting this plugin? I think it is more an HoneKit issue than a specific plugins one. As you tell, sensors are working from other devices…

**Comment by jerome71** [comment]
I was actually wondering whether this was an issue with the plugin.
I spend quite some time with Apple trying to solve the HomePod+Homebridge issue, until I read this had to do with the mDNS broadcaster in Homebridge. As soon as I changed it to Bonjour HAP the issue stoped.
But not for Mobile Alerts.
So I was wondering if there was a specific mDNS broadcaster hard coded in the Homebridge-mobile alerts plugin.
If that is not the case, then you are right, nothing to do here.
Have a great day :-)

**Comment by dehsgr** [comment]
Ok. Thanks for clarification. There isn't anything about mDNS within this plugin. So I'll close here. Have a nice weekend. :-)
