### ISSUE TITLE
HTTP Error Code 403

### ISSUE THREAD

**Issue by TomF79** [dehsgr/homebridge-mobilealerts#24]
After installing the plugin it come a Message about HTTP Error Code 403 and then every second Merging Sensor Data.
It has been working for the last weeks, since yesterday it has stopped working.

**Comment by TomF79** [comment]
<img width="820" alt="PNG-Bild" src="https://user-images.githubusercontent.com/93859783/150646455-647ed93d-a2e7-49ab-8ea7-90bfe8448919.png">

**Comment by dehsgr** [comment]
**Mobile Alerts Team locked us out again instead providing an adequate API to all users and sensors.** 

That's their default answer the second time now, if they have to much load on their systems. If they would provide an adequate API to all users for being able to fetch all sensors they wouldn't have such heavy load on their systems. :'(

A fix currently under implementation and will be published soon...

**Comment by dehsgr** [comment]
Duplicate to https://github.com/dehsgr/node-red-contrib-mobilealerts/issues/11

**Comment by TomF79** [comment]
Thanks for your quickly answer. I thougt ist was only my problem and install the homebridge many times new.

**Comment by dehsgr** [comment]
Published new version.
