### ISSUE TITLE
Accessory filter?

### ISSUE THREAD

**Issue by tiimjcb** [dehsgr/homebridge-mobilealerts#26]
Hey,
I'm setting up an homebridge, and I have a problem. On my Mobile Alerts Account, I have multiple sensors. 5 for my servers room at my office, and 3 at my house. I would like to keep only the 3 in my house for my Homebridge, but idk if it's possible, or not.
Thanks for your work! :)

**Comment by dehsgr** [comment]
I'll see what I can do for you. But currently I'm busy and cannot tell you any time frame.

**Comment by tiimjcb** [comment]
No problem! Take all the time you need, it's not an emergency.

**Comment by dehsgr** [comment]
Published new version including this feature.

**Comment by tiimjcb** [comment]
thanks for the fast react-time, and for your work!❤️
