### ISSUE TITLE
Home Assistant 

### ISSUE THREAD

**Issue by TomF79** [dehsgr/homebridge-mobilealerts#27]
Hi, thanks for your great plugin, it works fine and i like using it.
Was there any chance to get the same plugin for Home Assistant? There is nothing like this available.

PS: Sorry, i didnt found a other way to contact.

BR Tom

**Comment by dehsgr** [comment]
This should be requested in Home Assistant repository/forum. HA is a complete different platform I‘m currently not using and developing for.
