### ISSUE TITLE
Pollinginterval missing from sample config.json

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#29]
Without it, I get no sensor data.
The following line should be added to the sample config.json:
"pollinginterval": 420,

**Comment by dehsgr** [comment]
Polling interval isn‘t needed since v2. I would like you to send me your config for checking.

**Comment by dehsgr** [comment]
Okay. I can see where the issue is. After adding the sensors there isn't a call for updating sensor data.

Nevertheless old _pollinginterval_ parameter isn't needed anymore. This is because the plugin is using default of 420 secs now reflecting update interval of Mobile Alerts API.

**Comment by dehsgr** [comment]
This is fixed by [75859aa](https://github.com/dehsgr/homebridge-mobilealerts/commit/75859aa8f8922b682f6d3447bd30ea4f6685f1ca).
