### ISSUE TITLE
Updating to version 2.0 crashes all of homebridge

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#30]
This is more than annoying and could be averted by including defaults missing api parameters.

otherwise, please include a warning for upgrading to version 2

**Comment by dehsgr** [comment]
Mmmmhhh. Strange. Could you clarify which parameters are missing? There might be sth. missing, but this is unexpected. Could you post your (old) configuration?

**Comment by dehsgr** [comment]
Related to issue #31.

**Comment by dehsgr** [comment]
There is a missing setting check. Will publish a fix shortly.
