### ISSUE TITLE
Missing instructions for upgrading to version 2

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#31]
The following instructions should be included:

(do not remove the polling interval line)

Please go to the config tab of the Homebridge interface and add the following lines in the MobileAlerts section, as in the sample config.json file:

devices": [
   		"0123456789ABCDEF",	// sensor serial
   		"1234567890ABCDEF",	// sensor serial
   		"2345678901ABCDEF"	// sensor serial
   	],
   	"api": {				// -> fit this to app settings!
   		"language": "de",		
   		"ampm": false,		// use am/pm vs. 24h
   		"celsius": true,	// use °C vs. °F
   		"mm": true,			// use mm vs. in
   		"speedunit": 0		// 0=m/s; 1=km/h; 2=mph; 3=kn
   	},

Replace sensor serials with the values found on the Mobile Alerts app's dashboard.
Other languages might work

**Comment by dehsgr** [comment]
WHERE should these instructions be placed in?

**Comment by jerome71** [comment]
Probably should be at the beginning of the readme.md file.
Might not be needed if the pulgin still works after upgrading to 2.x.

**Comment by dehsgr** [comment]
@jerome71 should be working after last fixes related to issues #29  and #30. So I'll close here.

Thank you for your input – I really appreciated it!
