### ISSUE TITLE
Cannot allocate sensors to rooms

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#32]
After upgrading to V2.1.1, all my sensors are in HomeKit's default room.
I cannot change them in the Home app on iOS or macOS.
I can change the room for other Homebridge switches without problem.

**Comment by dehsgr** [comment]
This isn't a plugin-related bug. Seems to be an issue with latest iOS update. I'm able to reproduce it.

Workaround: 
1.  Chosse sensor you would like to move.
2. Open its room settings.
3. Change room.
4. Hit the cross to close settings.

The room gets reset only to the old one if you hit the room setting again.

@jerome71 I would like you to confirm.

**Comment by jerome71** [comment]
@dehsgr That works. Thanks!
