### ISSUE TITLE
Mergin Sensors 

### ISSUE THREAD

**Issue by ChSey** [dehsgr/homebridge-mobilealerts#33]
Hi! Since yesterday Homebridge cannot merge sensors anymore and I'm wondering why this is:
<img width="872" alt="Bildschirmfoto 2023-12-06 um 21 14 17" src="https://github.com/dehsgr/homebridge-mobilealerts/assets/153130555/dded6518-bb4f-4d70-b41d-28a3860bf334">
<img width="982" alt="Bildschirmfoto 2023-12-06 um 21 24 43" src="https://github.com/dehsgr/homebridge-mobilealerts/assets/153130555/0d696b0a-6dc8-457b-91d6-97002c74f021">

Thanks for your help!

**Comment by ellzzett** [comment]
I have the same issue since yesterday.

**Comment by jerome71** [comment]
Same issue for me.

The result is that I have the mobilealerts plugin produces no data at all. Does not work. (maybe I would change the title of this thread to make that clearer)

**Comment by dehsgr** [comment]
Just published [a fix](https://github.com/dehsgr/homebridge-mobilealerts/commit/924efc51226b8626f2a62fb4afd525c2d39bdaa0) to NPM as API endpoint changed.

**Comment by jerome71** [comment]
Works again. Thanks a lot @dehsgr 🙏🙏🙏

**Comment by ChSey** [comment]
Works again. Thanks so much @dehsgr for your fast response and help!
