### ISSUE TITLE
I get the names of the sensors but no data are read

### ISSUE THREAD

**Issue by yanmeyer** [dehsgr/homebridge-mobilealerts#4]
First thank you for your module, It would be very useful.

I have 3 plugins : broad link-platform, broad link-rm and now mobilealerts. When I start Homebridge, I get some Error: "Could not get Data for Sensor [sensor id]. Now I have 3 Sensors: 043196B14E51, 06154317ED5B, 0301548CBC4A.
The errors come back every minutes: 
[MobileAlerts] Fetching Data...
[MobileAlerts] Updating Accessory Data...
[MobileAlerts] Could not get Data for Sensor 043196B14E51
[MobileAlerts] Could not get Data for Sensor 06154317ED5B
[MobileAlerts] Could not get Data for Sensor 0301548CBC4A

In Home Bridge, the modules are created but no Data is visible, also for the Berlin sensor given for test.

Do you have any idea for me ? with best regards, Yannick, Switzerland

**Comment by dehsgr** [comment]
Thanks for getting in touch. It could be possible, that you've to modify RegEx according to Issue #3. Would you post HTML content from https://measurements.mobile-alerts.eu?

**Comment by dehsgr** [comment]
I committed a new Version here and at NPM. This Version should work, as I made this Version Language independent to Mobile Alerts Server Responses.

If this new Version isn't working for you again, don't hesitate to contact me again.

**Comment by yanmeyer** [comment]
Great, it is working perfectly. Excellent, thank you for the light speed job. Your work is really wildely extending the homekit possibilities. Have nice week.
