### ISSUE TITLE
Homebridge crashed (1.0.4)

### ISSUE THREAD

**Issue by marcoschmidt79** [dehsgr/homebridge-mobilealerts#5]
Hello, i have a problem. i use mobilealerts for a half year now. after update homebridge-mobilealerts 1.0.4 crashed homebridge after 12-24 hours. i make a new home and homebridge crashed after 24 hours also. then i installed 1.0.3 and homebridge run stable.

**Comment by dehsgr** [comment]
I would like you to provide a log from the crashing instance, so I may find out what the issue is. Currently I didn't get any feedback regarding this and know about 3 instances running without any issue. So it could helpful to get more information which (other) plugin you're using and so on...

**Comment by marcoschmidt79** [comment]
Hello, sorry, unfortunately I can not provide a protocol because I use version 1.0.3 again. plugins: "homebridge-broadlink-rm",
        "homebridge-alexa",
        "homebridge-camera-ffmpeg",
        "homebridge-config-ui-x",
        "homebridge-mi-gateway-security",
        "homebridge-milight",
        "homebridge-mobilealerts",
        "homebridge-mqtt-power-consumption-log-tasmota",
        "homebridge-mqtt-switch-tasmota",
        "homebridge-philipstv-x",
        "homebridge-platform-maxcube",
        "homebridge-telegram",
        "homebridge-mi-aqara"

the homebridge hang up by:

[MobileAlerts] Fetching Data...
[MobileAlerts] Updating Accessory Data...

**Comment by dehsgr** [comment]
I think you plugins are mostly common. Which version of Homebridge are you using? Which sensor ids are configured within mobile alerts (giving sensor types should be enough)?

I can‘t see any reason why the plugin should run for about 12 hours and then suddenly stop responding. The changes from last update are only reflecting the parsing HTML from MA servers. So I guess, that there might be a communication problem between your site and MA servers, while this issue occurs. But: this should happen on v1.0.3 too.

I‘ll check to implement an additional config value for being able to perform verbose logging. This could direct us in the right direction too...

**Comment by marcoschmidt79** [comment]
i use 5 x MA10200, one MA10100, one MA10006. my homebridge-version is 0.4.45 and node 10.10.0.

PS where are you from?

**Comment by dehsgr** [comment]
Okay. I take a look on that sensors. Homebridge and Node I would exclude as well.

PS: from Germany ;-)

**Comment by marcoschmidt79** [comment]
Prima, auf Deutsch kann ich es besser erklären. Ich habe vor 5 Tagen, direkt am Updatetag das Plugin aktualisiert. So ziemlich genau nach 24 Stunden war Schicht im Schacht. Anschließend habe ich alles mögliche versucht, Homebridge wieder zum Laufen zu bekommen. Accessoires gelöscht, Persist gelöscht, Plugin deaktiviert. Keine Chance. Das Einzige, was half, war username, port und pin ändern, also neues zu Hause, was mit entsprechender Arbeit verbunden war bei 67 Geräten, Szenen waren auch weg. Fast 24 Stunden später wieder crash, Homebridge hing laut log erneut bei [MobileAlerts] Fetching Data...
[MobileAlerts] Updating Accessory Data...
Also 1.0.3. drauf und läuft wieder problemlos. Vorher lief Homebridge seit über einem halben Jahr problemlos.

**Comment by dehsgr** [comment]
Auch gut - machen wir auf Deutsch weiter. ;-)

Eine wirkliche Erklärung habe ich gerade nicht. Insbesondere, da ich Deine Sensoren teilweise auch einsetze. Ich werde noch heute eine Version veröffentlichen, in der ich das erweiterte Logging eingebaut habe, damit wir mal sehen können, ob evtl. bestimmte Werte nicht (mehr korrekt) ausgelesen werden können. Evtl. kommen wir dem Ganzen dann etwas zielführender auf die Spur.

Kann natürlich im Rahmen der Abschaffung der Sprachabhängigkeit passiert sein (beim MA10350-Datenpunkt "Leckage" habe ich gerade auch einen Typo entdeckt), dass Werte nicht mehr korrekt ausgelesen werden, aber so richtig mag ich es nicht glauben, da die Abfragen nach erneuter Review soweit korrekt sind.

Wärst Du so frei, mir mal den HTML-Source von https://measurements.mobile-alerts.eu oder die iPhone-ID an [E-Mail-Adresse entfernt] zu senden? Die Daten behandle ich natürlich vertraulich und vernichte Sie nach Diagnose wieder.

**Comment by marcoschmidt79** [comment]
Ja, hab sie dir geschickt. :-)

**Comment by dehsgr** [comment]
Super! Du hast mir Deinen MA10350 verschwiegen. ;-)

Ich habe gerade die neue Version veröffentlich. Bitte spiele diese mal ein und füge in Deiner config.json gemäß Beispiel unter 
https://github.com/dehsgr/homebridge-mobilealerts/blob/master/sample-config.json folgende zusätzliche Einstellungen ein:

`"log": {
                "verbose": false,
                "HTML": false
            }`

Sollte der Fehler anschließend wieder auftreten, würde ich Dich bitten, mir das erweiterte Log zukommen zu lassen.

**Comment by marcoschmidt79** [comment]
Lass mich das Sonntag Abend machen, Montag hab ich mehr Zeit, alles neu zu sortieren. :-) 
Verrate mir noch bitte, wie ich das mit dem erweiterten Log anstelle, Ausgabe bitte in eine Datei. 

            "platform": "MobileAlerts",
            "name": "MobileAlerts",
            "iphoneid": "xxxxxxxxxxxxxx",
            "log": { "verbose": false, "HTML": false }

So wäre dann korrekt, oder?

**Comment by dehsgr** [comment]
Korrekt. Wie Du protokollierst, hängt davon ab, wo Deine Homebridge hinschreibt (abhängig davon, wie sie startet). Bei Systemd-Nutzung solltest Du alles unter /var/log/syslog finden...

**Comment by marcoschmidt79** [comment]
So, ist aktualisiert, mal schaun.

**Comment by dehsgr** [comment]
Und? Kannst Du schon etwas Neues berichten?

**Comment by marcoschmidt79** [comment]
He, also bis jetzt stabil ohne Absturz mit 1.0.5 und dem Log-Eintrag in der Config.

**Comment by dehsgr** [comment]
Freut mich sehr zu hören. Ich kann es mir zwar nach wie vor nicht wirklich erklären, aber wenn es läuft bin ich zufrieden. ;-)

Ich würde mich natürlich noch mehr freuen, wenn ich von Dir zum Wochenende das Feedback bekäme, dass ich damit den Eintrag schließen kann...

**Comment by marcoschmidt79** [comment]
Jep, ich melde mich nochmal, danke.

**Comment by marcoschmidt79** [comment]
Sep 20 06:39:04 homebridge homebridge[19066]: [2018-9-20 06:39:04] [Deckenlampe Flur] Deckenlampe Flur  - Power from State OFF
Sep 20 06:39:06 homebridge homebridge[19066]: [2018-9-20 06:39:06] [Camera-ffmpeg] Snapshot from Kamera at 480x270
Sep 20 06:39:14 homebridge homebridge[19066]: [2018-9-20 06:39:14] [Broadlink] Broadlink RM device at 192.168.5.100 (0d:43:b4:a1:20:b9) is no longer reachable.
Sep 20 06:39:16 homebridge homebridge[19066]: [2018-9-20 06:39:16] [Schalter TV] Schalter TV  - Power from State ON
Sep 20 06:39:17 homebridge homebridge[19066]: [2018-9-20 06:39:17] [Fernseher] Fernseher  - Power from State ON
Sep 20 06:39:18 homebridge homebridge[19066]: Broadlink RM device at 192.168.5.100 (0d:43:b4:a1:20:b9) has been re-discovered.
Sep 20 06:39:25 homebridge homebridge[19066]: [2018-9-20 06:39:25] [Camera-ffmpeg] Snapshot from Kamera at 480x270
Sep 20 06:39:31 homebridge homebridge[19066]: [2018-9-20 06:39:31] [Lampe Esszimmer rechts] Lampe Esszimmer rechts  - Power from State ON
Sep 20 06:39:32 homebridge homebridge[19066]: [2018-9-20 06:39:32] [MobileAlerts] Fetching Data...
Sep 20 06:39:33 homebridge homebridge[19066]: [2018-9-20 06:39:33] [MobileAlerts] Updating Accessory Data...

Hängt wieder fest.

**Comment by dehsgr** [comment]
Ich sehe gerade: Du hast (leider) vergessen, die beiden Log-Einträge auf „true“ (von „false“) zu ändern.

Bitte nochmals durchführen, Homebridge neu starten und neues Log posten (gerne auch ein längeres).

Btw: Was ist Dein Broadlink RM Device? Da sehe ich eine Unterbrechung!

**Comment by marcoschmidt79** [comment]
ok heut abend. Broadlink ist ne Ferbedienung, das ist normal.

**Comment by dehsgr** [comment]
Da das neue Log sensible Daten erhält, schlage ich vor, dass Du es dann an die Dir bekannte Mail-Adresse sendest...

**Comment by dehsgr** [comment]
Gibt es schon neue Ergebnisse? Und bitte nicht immer gleich HB neu installieren. Das bekommen wir auch so noch zum laufen...

**Comment by marcoschmidt79** [comment]
He, sorry, grad erst Update gemacht und neugestartet. :-D Ich meld mich.

**Comment by marcoschmidt79** [comment]
Mail ist raus. :-)

**Comment by dehsgr** [comment]
Super! Damit kommen wir weiter. Was ich feststellen konnte ist die Tatsache, dass Deine Wetterstation zum Zeitpunkt des Absturzes/Hängens keine Daten mehr für den Außensensor geliefert hat. Da ist jetzt zum einen die Frage auf Deiner Seite zu beantworten, warum das der Fall ist. Zum Anderen muss ich jetzt mal schauen, warum das Plugin deshalb aussteigt, obwohl es letztlich protokollieren sollte, dass es keine Daten erhalten hat. Also machen wir jetzt beide mal unsere Hausaufgaben. Wenn Du etwas herausfindest, meldest Du Dich bitte hier und ich melde mich hier ebenfalls, wenn ich soweit bin. ;-)

PS: Ein Neustart der HB sollte diese wieder zum Laufen bewegen (bis zum nächsten Hänger)...

**Comment by marcoschmidt79** [comment]
He, grüß dich. Keine Ahnung, warum der Außensensor keine Daten lieferte, hier sieht alles normal aus. Ich tausche mal die Batterien. Der Sensor hängt 3 m von der Wetterstation weg, an der Entfernung liegt es also nicht. Das wird aber auch unter 1.0.3 so sein, nur steigt das Plugin da nicht aus. Ja, Neustart der Homebridge reicht aus, allerdings dauert dieser nach dem Plugin-Crash sehr lang, warum auch immer, was damals der Grund war, dass ich ein neues Haus angelegt habe. Aber mittlerweile bleibt mir wenigstens das erspart. :-)

**Comment by dehsgr** [comment]
Zwischen 1.0.3 und 1.0.4 hat sich in der Tat die Abfrage der Daten ein wenig verändert, warum aktuell das Plugin empfindlicher zu reagieren scheint. Das sehe ich mir in jedem Fall an und werde vermutlich noch heute ein Update bereitstellen.

Der Crash passierte gegen 5:30 Uhr. Evtl hatte dort das MA-Gateway auch gerade keinen Kontakt zum Internet, weil evtl. eine Zwangstrennung durch Deinen Provider stattfand und konnte deshalb die Daten nicht ordnungsgemäß übermitteln...

**Comment by marcoschmidt79** [comment]
![img_6077 copy](https://user-images.githubusercontent.com/37773833/45926233-abfad000-bf20-11e8-9193-b198eca229f5.png)

Nach der üblichen Zwangstrennung sieht es nicht aus, aber der Außensensor hat tatsächlich um 5:30 Uhr kurz keine Daten geliefert, warum auch immer.

PS: Meine Zwangstrennung war um 4:50 Uhr. Um 5:30 meldet der Router kein Ereignis: 

23.09.2018 05:53:41DHCP ist aktiv: 23.09.2018 xx:xx:xx xxxx::1 (DH101)
23.09.2018 05:01:51DHCP ist aktiv: 23.09.2018 xx:xx:xx xxxx::1 (DH101)

**Comment by dehsgr** [comment]
Ich habe die Korrektur nun als Update veröffentlicht. Damit mache ich hier erst einmal dicht. Sollte wider Erwarten doch noch ein Fehler auftreten, einfach nochmal melden.

Herzlichen Dank für die hervorragende Zusammenarbeit! ;-)

**Comment by marcoschmidt79** [comment]
Ich danke dir, es war mir eine Freude. Update ist drauf, warten wirs ab. :-)
