### ISSUE TITLE
Sensor MD 10120Pro

### ISSUE THREAD

**Issue by ProfMW** [dehsgr/homebridge-mobilealerts#7]
Hello,

i'm using Mobile Alerts (TFA Weatherhub) with sensor MA10100 and MA10120Pro. Now i try out home bridge with your plugin. The sensor MA10100 works very well. Is there a way to support the other sensor? I would like to support you.

Thank's from Germany!

**Comment by dehsgr** [comment]
Hey @ProfMW,

This shouldn‘t be a problem. I need one of two things for supporting this sensor:

- Your MA-ID -or-
- The HTML source from sensor overview at https://measurements.mobile-alerts.eu

Thank you!

**Comment by ProfMW** [comment]
Hallo,
the MA-ID [removed for security reasons] . The name of the sensor is "Draussen" . It's outside in german.
Do you need the phone-ID too?
Thank you!

**Comment by dehsgr** [comment]
No. phone-ID isn't needed. I just take a look.

**Comment by dehsgr** [comment]
MA 10120 is implemented now.
