### ISSUE TITLE
Missing support for Mobile Alerts temperature sensor MA 10101 in Homebridge

### ISSUE THREAD

**Issue by shroudy86** [dehsgr/homebridge-mobilealerts#8]
Hello everybody,

i bought the Mobile Alerts sensor MA 10101 to control my seawater fish tank. It works great, but it would be really cool if i can ask siri for temperature or control it in homekit app. 

I see that some other sensors 
MA 10006
MA 10100
MA 10120
MA 10200
MA 10320
MA 10350
MA 10700 are available but not mine :(. It seems like a simple temperature sensor (like MA 10100), but only with 1 sensor and not 2. Is it hard to support it?

Thank you very much!!

Best regards
Patrick :)

**Comment by shroudy86** [comment]
Oh and i forgot the MA ID of the sensor is `` the sensor is called Aquarium. Do you need more informations? Thank you so much!

**Comment by dehsgr** [comment]
Hey Patrick,

I just checked the code. Are you sure it isn't working? If I add your sensor I get it embedded at my homebridge.

Thank you,

Sebastian

**Comment by shroudy86** [comment]
![32ABFCFD-19DB-4AEB-8FFC-AB5E2A98BB9E](https://user-images.githubusercontent.com/50516550/57586458-7d088d00-74f6-11e9-83ce-e03c3d3efb79.png)
![0194E2B6-D411-4DE8-A49F-7BCDD63FBC44](https://user-images.githubusercontent.com/50516550/57586459-7d088d00-74f6-11e9-83e8-37f3be2d5dc4.png)

Hey Sebastian,

thank you so much for your fast respond. Hmm, so i really have no idea, why i can‘t see the sensor in my HomeKit App.. i use homebridge for some other plugins (like Rademacher Rollotron for example) and they work. So i can’t believe this is a problem of my homebridge configuration.

Maybe i have the wrong settings?

**Comment by shroudy86** [comment]
Omg, this is so embarrassing :-D...

There was two space signs before and behind the entrys.

So sorry for this!

Thank you again for your support and the Plugin 👍

Patrick

**Comment by dehsgr** [comment]
Okay. No Problem. Nobody is perfect. I'm happy this is working for you now. I just checked it here and got it working too.. ;-)
