### ISSUE TITLE
Add new devices MA10421 and MA MA10001

### ISSUE THREAD

**Issue by jerome71** [dehsgr/homebridge-mobilealerts#9]
Hi.

I would like to help add 2 Mobile alert devices:
- MA10001 which is the internet gateway with 1 temperature sensor,
- MA10421 which has 4x(temperature+humidity) :  1 for the base + 3 other sensors

-MA10001 is already recognized although not on the supported device list
-MA10421 shows as not supported.

I'd like to help in any way. I haven't coded for decades though. I'd happily provide my iphone ID.

**Comment by dehsgr** [comment]
I would like you to provide your iPhone-ID via dehsgr at outlook dot com.

**Comment by jerome71** [comment]
Just sent my iPhone-ID.

**Comment by dehsgr** [comment]
I just implemented MA10421 support and corrected ReadMe. I would like you to provide your feedback if it is running as expected.

**Comment by jerome71** [comment]
Hi.

I just updated the module, and re-added the homebridge to Homekit.
The MA10421 appears as 4 temperature sensors + 4 humidity sensors.
But they all show 0°C or 0%.
(they appear correctly in the Mobile Alerts app)

Have a great day,
Jérôme.

**Comment by dehsgr** [comment]
Ok. Just fixed that. Could process values now correctly.

**Comment by jerome71** [comment]
Works well now. Thanks.
